/*
 * DemoViewertestSuite.java
 * JUnit based test
 *
 * Created on 2006. január 22., 23:54
 */

package demoviewer;

import junit.framework.*;

/**
 *
 * @author vear
 */
public class DemoViewertestSuite extends TestCase {
    
    public DemoViewertestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("DemoViewertestSuite");
        return suite;
    }
    
}
